version: '3.7'
services:
    web:
        image: nginx:latest
        ports:
            - "1000:80"
            - "1001:443"
        expose:
            - "1001"
        volumes:
            - ./code:/var/www/html/code
            - ./docker/nginx/ssl:/etc/nginx/ssl
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
        networks:
            - soa
    php:
        build: docker/php
        volumes:
            - ./code:/var/www/html/code
        networks:
            - soa
    postman_checks:
        build: docker/newman
#        command:
#            run test_postman_collection.json --insecure
#            -e test_postman_environment.json
#            -r cli
        links:
            - web
        volumes:
            - ./postman:/etc/newman
        networks:
            - soa
networks:
    soa:
        external: true
