language: php

php:
    - '7.4'

services:
    - docker

cache: bundler

jobs:
    fast_finish: true

env:
    global:
        - DOCKER_COMPOSE=1.24.1
    matrix:
        - PROJECT=auth
        - PROJECT=message
        - PROJECT=cloud-storage
        - PROJECT=application

sudo: required

before_install:
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
install:
    - cd $PROJECT
    - docker network create -d bridge soa
    - docker-compose up --build php

before_script:
    - docker-compose exec php sh -c "php -d memory_limit=-1 composer.phar install -n"
    - docker-compose exec php sh -c "sh post-install.sh"
script:
    - docker-compose exec php sh -c "vendor/bin/phpcs --standard=PSR2 src/"
    - docker-compose exec php sh -c "vendor/bin/psalm"
    - docker-compose exec php sh -c "vendor/bin/phpunit tests/"
    - docker-compose run postman_checks

notifications:
    slack: dykyiroman:TeCiTtXOYLiODNR1iBB6H5Oy