language: php

php:
    - '7.4'

services:
    - docker

env:
    - PROJECT=auth
    - PROJECT=message

sudo: required

before_install:
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin

install:
    - cd $PROJECT
    - docker network create -d bridge soa
    - docker-compose build
    - docker-compose up -d php

before_script:
    - docker-compose exec php sh -c "cd code && php -d memory_limit=-1 composer.phar install -n"
    - docker-compose exec php sh -c "cd code && php bin/console --no-interaction doctrine:migrations:migrate"
    - docker-compose exec php sh -c "cd code && php bin/console --env=test --no-interaction doctrine:migrations:migrate"
script:
    - docker-compose exec php sh -c "cd code && php vendor/bin/phpcs --standard=PSR2 src/"
    - docker-compose exec php sh -c "cd code && php vendor/bin/psalm"
    - docker-compose exec php sh -c "cd code && php vendor/bin/phpunit tests/"
#    - docker-compose run postman_checks
