web:
    image: nginx:latest
    ports:
        - "8080:80"
        - "443:443"
    expose:
        - "443"
    volumes:
        - ./code:/code
        - ./ssl:/etc/nginx/ssl
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    build: docker/php
    volumes:
        - ./code:/code
    links:
        - mysql
mysql:
    image: mysql
    restart: always
    volumes:
      - ./database/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_PORT: 3306
    ports:
      - "3306:3306"
    expose:
      - "3306"
adminer:
    image: adminer
    restart: always
    links:
        - mysql
    ports:
        - 8888:8080