version: '3.7'
services:
    web:
        build:
            context: docker/nginx
        ports:
            - "5000:80"
            - "5001:443"
        expose:
            - "5001"
        volumes:
            - ./code:/var/www/html/code
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
        networks:
            - soa
    php:
        build: docker/php
        volumes:
            - ./code:/var/www/html/code
        links:
            - mysql
        networks:
            - soa
    mysql:
        image: mysql:8.0
        restart: always
        command: --init-file /docker-entrypoint-initdb.d/init.sql
        volumes:
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./database/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_PORT: 5003
        ports:
            - "5003:3306"
        expose:
            - "5003"
        networks:
            - soa
    adminer:
        image: adminer
        restart: always
        links:
            - mysql
        ports:
            - 5004:8080
        networks:
            - soa
    postman_checks:
        build: docker/newman
        command:
            run test_postman_collection.json --insecure
            -e test_postman_environment.json
            -r cli
        links:
            - web
        volumes:
            - ./postman:/etc/newman
        networks:
            - soa
networks:
    soa:
        external: true
