admin.template.create:
    path: /api/template/
    controller: App\UI\Api\TemplateController::create
    methods: POST

admin.template.update:
    path: /api/template/{id}
    controller: App\UI\Api\TemplateController::update
    methods: PUT

admin.template.delete:
    path: /api/template/{id}
    controller: App\UI\Api\TemplateController::delete
    methods: DELETE