version: '3.7'
services:
    web:
        image: nginx:latest
        ports:
            - "6000:80"
            - "6001:443"
        expose:
            - "6001"
        volumes:
            - ./code:/code
            - ./docker/nginx/ssl:/etc/nginx/ssl
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
        networks:
            - soa
    php:
        build: docker/php
        volumes:
            - ./code:/code
        links:
            - mongo
        networks:
            - soa
    redis:
        image: redis
        command: ["redis-server", "--appendonly", "yes"]
        networks:
            - soa
        volumes:
            - redis-data:/data
    mongo:
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGO_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD}'
            MONGO_INITDB_DATABASE: '${MONGO_DATABASE}'
        ports:
            - 6002:27017
        volumes:
            - ./docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        networks:
            - soa
    mongo-express:
        image: mongo-express
        restart: always
        depends_on:
            - mongo
        ports:
            - 6003:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: secret
        networks:
            - soa
networks:
    soa:
        external: true

volumes:
    redis-data: