version: '3.7'
services:
    web:
        build:
            context: docker/nginx
        ports:
            - "6000:80"
            - "6001:443"
        expose:
            - "6001"
        volumes:
            - ./code:/var/www/html/code
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
        networks:
            - soa
    php:
        build: docker/php
        command: '/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf'
        volumes:
            - ./code:/var/www/html/code
            - ./code/config/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        links:
            - redis
        networks:
            - soa
    redis:
        image: redis
        command: ["redis-server", "--appendonly", "yes"]
        networks:
            - soa
        volumes:
            - redis-data:/data
    postman_checks:
        build: docker/newman
        command:
            run test_postman_collection.json --insecure
            -e test_postman_environment.json
            -r cli
        links:
            - web
        volumes:
            - ./postman:/etc/newman
        networks:
            - soa
networks:
    soa:
        external: true

volumes:
    redis-data: