{
 "title": "Message metrics",
 "tags": [ "message" ],
 "time": { "from": "2020-04-05T06:39:14.084Z", "to": "2020-04-05T08:39:14.084Z" },
 "templating": {
  "list": [
   { "name": "type", "label": "type", "query": "message_sent_timing" }
  ]
 },
 "panels": [
  {
   "title": "Message timing",
   "type": "graph",
   "description": "Message timing",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(message_sent_timing{job=\"statsd-exporter\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Message sent status",
   "type": "graph",
   "description": "Message service",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(message_sent_timing_count{job=\"statsd-exporter\"}[1m])) by (error, type)",
     "legendFormat": "error={{error}}"
    }
   ]
  },
  {
   "title": "Template",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(message_template_load_count{job=\"statsd-exporter\"}[1m]))",
     "legendFormat": "template load"
    }
   ]
  }
 ]
}