doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: false
    hydrator_namespace: Hydrators
    hydrator_dir: '%kernel.cache_dir%/doctrine/odm/mongodb/Hydrators'
    connections:
        default:
            server: '%env(resolve:MONGODB_URL)%'
            options:
                username: '%env(resolve:MONGODB_USER)%'
                password: '%env(resolve:MONGODB_PASSWORD)%'
    default_database: '%env(resolve:MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                Sender:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Domain/Sender/Document'
                    prefix: 'App\Domain\Sender\Document'
                    alias: App
                Template:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Domain/Template/Document'
                    prefix: 'App\Domain\Template\Document'
                    alias: App