controllers:
    resource: '../src/UI/Http/'
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

gesdinet_jwt_refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh

api_login_check:
    path: /api/user/login