register:
    path: /api/user/registration
    controller: App\UI\Controller\AuthController::register
    methods: POST

user:
    path: /api/user/{id}
    controller: App\UI\Controller\UserController::user
    methods: GET

gesdinet_jwt_refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh

api_login_check:
    path: /api/user/login