version: '3.7'
services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
            - "443:443"
        expose:
            - "443"
        volumes:
            - ./code:/code
            - ./ssl:/etc/nginx/ssl
            - ./site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
    php:
        build: docker/php
        volumes:
            - ./code:/code
        links:
            - mongo
            - rabbit
    mongo:
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGO_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD}'
            MONGO_INITDB_DATABASE: '${MONGO_DATABASE}'
        ports:
            - 27017:27017
        volumes:
            - ./docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    mongo-express:
        image: mongo-express
        restart: always
        depends_on:
            - mongo
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: secret
    rabbit:
        image: "rabbitmq:3-management"
        environment:
            RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
            RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
            RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
            RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_DEFAULT_VHOST}"
        ports:
            - 15672:15672
            - 5672:5672
        volumes:
            - ./docker/rabbit/enabled_plugins:/etc/rabbitmq/enabled_plugins"