version: '3.7'
services:
    web:
        image: nginx:stable-alpine
        ports:
            - "4000:80"
            - "4001:443"
        expose:
            - "4001"
        volumes:
            - ./code:/var/www/html/code
            - ./docker/nginx/ssl:/etc/nginx/ssl
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
        networks:
            - soa
    php:
        build: docker/php
        command: '/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf'
        volumes:
            - ./code:/var/www/html/code
            - ./code/config/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        links:
            - mongo
            - rabbit
        networks:
            - soa
    redis:
        image: redis
        command: ["redis-server", "--appendonly", "yes"]
        networks:
            - soa
        volumes:
            - redis-data:/data
    mongo:
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGO_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD}'
            MONGO_INITDB_DATABASE: '${MONGO_DATABASE}'
        ports:
            - 4002:27017
        volumes:
            - ./docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        networks:
            - soa
    mongo-express:
        image: mongo-express
        restart: always
        depends_on:
            - mongo
        ports:
            - 4003:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: secret
        networks:
            - soa
    rabbit:
        image: "rabbitmq:3-management"
        environment:
            RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
            RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
            RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
            RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_DEFAULT_VHOST}"
        ports:
            - 4004:15672
            - 4005:5672
        volumes:
            - ./docker/rabbit/enabled_plugins:/etc/rabbitmq/enabled_plugins"
        networks:
            - soa
    postman_checks:
        build: docker/newman
        command:
            run test_postman_collection.json --insecure
            -e test_postman_environment.json
            -r cli
        links:
            - web
        volumes:
            - ./postman:/etc/newman
        networks:
            - soa
networks:
    soa:
        external: true

volumes:
    redis-data: