version: '3.7'
services:
    mongo:
        image: mongo:3
        networks:
            - soa
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
        environment:
            - http.host=0.0.0.0
            - transport.host=localhost
            - network.host=0.0.0.0
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        deploy:
            resources:
                limits:
                    memory: 1g
        networks:
            - soa
    graylog:
        image: graylog/graylog:3.2
        container_name: graylog
        environment:
            # CHANGE ME (must be at least 16 characters)!
            - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}
            # Password: admin
            - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
            - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
        depends_on:
            - mongo
            - elasticsearch
        ports:
            # Graylog web interface and REST API
            - 9000:9000
            # Syslog TCP
            - 1514:1514
            # Syslog UDP
            - 1514:1514/udp
            # GELF TCP
            - 12201:12201
            # GELF UDP
            - 12201:12201/udp
        networks:
            - soa
networks:
    soa:
        external: true